### ISSUE TITLE
module 'objc' has no attribute 'initFrameworkWrapper'

### ISSUE THREAD

**Issue by abhishek-junghare** [jenskutilek/MasterGrid#7]
```
A plugin caused a crash

The Plugin MasterGrid.glyphsReporter has caused a crash. Please update it by opening the Plugin Manager or re-downloading it from the original source.

Details:
Traceback (most recent call last):

  File "plugin.py", line 8, in <module>
    from GlyphsApp import Glyphs, Message, OFFCURVE

  File "GlyphsApp/GlyphsApp/__init__.py", line 20, in <module>

AttributeError: module 'objc' has no attribute 'initFrameworkWrapper'

App:3.1-3133 Plugin:0.3.5-13
```

**Comment by jenskutilek** [comment]
Sorry, can't reproduce. What Python are you using (Glyphs, python.org, ...?) and which version of pyobjc do you have installed?

**Comment by abhishek-junghare** [comment]
Python 3.10.8
pyobjc 9.0

**Comment by abhishek-junghare** [comment]
Okay, I changed python from homebrew to glyphs. Now it doesn't crash. Thanks!
